### ISSUE TITLE
remove 'yeast' from species aliases

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#57]
It matches the wrong yeast for paper 00048930

**Comment by draciti** [comment]
besides Pichia Pastoris (correct) it also extracts 'Saccharomyces cerevisiae S288C' (not correct). 
And it does not extract 'Arthrobotrys oligospora'

**Comment by valearna** [comment]
I removed 'yeast' from the list of species aliases, and this should fix the problem, but I don't understand your additional comment @draciti.

**Comment by draciti** [comment]
I mean that it did not fix the problem entirely:
Saccharomyces cerevisiae in no longer extracted **_but_**
Saccharomyces cerevisiae S288C  is extracted and should not.

**_In Addition_**
'A oligospora' is mentioned 26 times and was not extracted

**Comment by valearna** [comment]
Ok, thanks @draciti. I will manually process the paper to understand what's going on

**Comment by valearna** [comment]
I've just re-run the pipeline on that paper. I probably forgot to re-run it after I fixed the error. Can you check if the list of species is ok?

**Comment by draciti** [comment]
works well- closing
